In [10]:
import pandas as pd
import numpy as np

df = pd.read_json("../data/pp_train.json")
# string_cols = ["coach_id", "player_id", "club_id", "season_id",
#                "validity_start_year", "validity_start_month", "validity_start_day",
#                "validity_end_year", "validity_end_month", "validity_end_day",
#                "date_of_birth_year", "date_of_birth_month", "date_of_birth_day"]
string_cols = ["coach_id", "player_id", "club_id"]

df[string_cols] = df[string_cols].astype(str)

In [11]:
df.season_id.value_counts()

season_id
2018    5624
2016    5357
2019    5237
2011    5180
2014    5018
2017    4988
2010    4929
2012    4702
2013    4512
2015    4146
Name: count, dtype: int64

In [12]:
print(df.shape)

(49693, 44)

In [4]:
# df["player_id"] = df["player_id"].astype(str)
# df["coach_id"] = df["coach_id"].astype(str)
# df["club_id"] = df["club_id"].astype(str)
# df["pseudonym"] = df["pseudonym"].replace("", "N/A")
# df.fillna("N/A", inplace=True)
# df.head()
# print(df["coach"].iloc[0])

In [5]:
df.head()

,injury_category,market_value_category,age,coach_id,player_id,club_id,league_id,season_id,injury,last_transfer_fee,...,validity_end_day,date_of_birth_year,date_of_birth_month,date_of_birth_day,reason_regular_interval,reason_new_coach,reason_transfer,reason_market_value_update,reason_injury,reason_injury_end
0,N/A,VERY LOW,36,1,6,-1,N/A,2010,N/A,0,...,30,1973,8,6,0,0,1,0,0,0
1,N/A,VERY HIGH,32,2,10,27,L1,2010,N/A,0,...,12,1978,6,9,1,0,0,0,0,0
2,general,VERY HIGH,32,2,10,27,L1,2010,Torn muscle fiber,0,...,9,1978,6,9,0,0,0,0,1,0
3,N/A,VERY HIGH,32,2,10,27,L1,2010,N/A,0,...,11,1978,6,9,0,0,0,0,0,1
4,N/A,VERY HIGH,32,2,10,27,L1,2010,N/A,0,...,29,1978,6,9,0,0,0,1,0,0

In [13]:
from synthcity.plugins import Plugins
from synthcity.plugins.core.dataloader import GenericDataLoader

tvae = Plugins().get("tvae") # can edit iterations here
tvae.fit(df)

[2025-04-16T22:13:30.949913+0200][19092][CRITICAL] module disabled: /Users/bep/git/uni/synthcity/src/synthcity/plugins/generic/plugin_goggle.py
[2025-04-16T22:13:30.951020+0200][19092][CRITICAL] load failed: module 'synthcity.plugins.generic.plugin_bayesian_network' has no attribute 'plugin'
[2025-04-16T22:13:30.951504+0200][19092][CRITICAL] load failed: module 'synthcity.plugins.generic.plugin_bayesian_network' has no attribute 'plugin'
[2025-04-16T22:13:30.952453+0200][19092][CRITICAL] module plugin_bayesian_network load failed
[2025-04-16T22:13:30.953482+0200][19092][CRITICAL] load failed: module 'synthcity.plugins.privacy.plugin_decaf' has no attribute 'plugin'
[2025-04-16T22:13:30.954235+0200][19092][CRITICAL] load failed: module 'synthcity.plugins.privacy.plugin_decaf' has no attribute 'plugin'
[2025-04-16T22:13:30.954721+0200][19092][CRITICAL] module plugin_decaf load failed
[2025-04-16T22:13:30.955337+0200][19092][CRITICAL] load failed: module 'synthcity.plugins.privacy.plugin_privbayes' has no attribute 'plugin'
[2025-04-16T22:13:30.955716+0200][19092][CRITICAL] load failed: module 'synthcity.plugins.privacy.plugin_privbayes' has no attribute 'plugin'
[2025-04-16T22:13:30.956093+0200][19092][CRITICAL] module plugin_privbayes load failed
 40%|████      | 400/1000 [12:32<18:48,  1.88s/it]

In [14]:
from synthcity.utils.serialization import save_to_file, load_from_file

save_to_file("tvae_16_04_third_numerical.pkl", tvae)

In [15]:
training_data_sample_size = df.shape[0]
samples = tvae.generate(count=training_data_sample_size)
samples_df = samples.dataframe()
samples_df

,injury_category,market_value_category,age,coach_id,player_id,club_id,league_id,season_id,injury,last_transfer_fee,...,validity_end_day,date_of_birth_year,date_of_birth_month,date_of_birth_day,reason_regular_interval,reason_new_coach,reason_transfer,reason_market_value_update,reason_injury,reason_injury_end
0,N/A,HIGH,27,141,24634,164,GB1,2018,Muscular problems,13234192,...,4,1989,7,5,0,0,0,1,0,0
1,pelvis,VERY HIGH,28,57,86175,167,L1,2018,Hairline fracture in the foot,20540669,...,21,1995,5,5,0,0,0,0,1,0
2,N/A,HIGH,29,161,11663,27,L1,2018,N/A,3067,...,26,1999,7,29,0,0,0,1,0,0
3,N/A,LOW,22,1,192268,984,N/A,2018,N/A,3047,...,30,1993,10,5,0,0,0,1,0,0
4,N/A,HIGH,26,168,18533,281,GB1,2018,N/A,95890,...,24,1992,9,21,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49688,N/A,LOW,24,1,3356,405,L1,2018,N/A,632129,...,30,1998,12,10,0,0,0,1,0,0
49689,misc,VERY HIGH,20,26,31910,3008,GB1,2018,Appendicitis,92686826,...,30,1996,9,8,0,0,0,0,1,0
49690,N/A,HIGH,26,92,81202,4,L1,2018,N/A,61390,...,16,1984,1,3,0,1,0,0,0,0
49691,illness,VERY LOW,21,161,256773,1071,GB1,2018,Hairline fracture in the foot,30293,...,21,1995,11,17,0,0,0,1,0,0
49692,N/A,VERY LOW,23,164,1791,23826,L1,2018,N/A,41768,...,4,1996,2,20,0,0,0,1,0,0

In [16]:
samples_df.season_id.value_counts()

season_id
2018    49689
2014        2
2010        1
2019        1
Name: count, dtype: int64

In [9]:
samples_df.to_json("tvae_full_16_04_third_numerical.json", orient="records")